"""add_satisfaction_and_response_times

Revision ID: 842ef0fb7aab
Revises: 
Create Date: 2026-09-13 09:26:50.906466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842ef0fb7aab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('fecha_primera_respuesta', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('calificacion', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('comentario_calificacion', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('fecha_calificacion', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('tickets_estado_check'), 'tickets', type_='check')
    op.create_check_constraint('ck_tickets_calificacion', 'tickets', 'calificacion IS NULL OR (calificacion >= 1 AND calificacion <= 5)')
    op.create_check_constraint('ck_tickets_estado', 'tickets', "estado IN ('Creado', 'En Ejecución', 'Solucionado')")
    op.alter_column('usuarios', 'cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuarios', 'area',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('usuarios_rol_check'), 'usuarios', type_='check')
    op.create_check_constraint('ck_usuarios_rol', 'usuarios', "rol IN ('Usuario', 'Soporte', 'Administrador')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_usuarios_rol', 'usuarios', type_='check')
    op.create_check_constraint(op.f('usuarios_rol_check'), 'usuarios', "rol::text = ANY (ARRAY['Usuario'::character varying, 'Soporte'::character varying, 'Administrador'::character varying]::text[])")
    op.alter_column('usuarios', 'area',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('ck_tickets_estado', 'tickets', type_='check')
    op.drop_constraint('ck_tickets_calificacion', 'tickets', type_='check')
    op.create_check_constraint(op.f('tickets_estado_check'), 'tickets', "estado::text = ANY (ARRAY['Creado'::character varying, 'En Ejecución'::character varying, 'Solucionado'::character varying]::text[])")
    op.drop_column('tickets', 'fecha_calificacion')
    op.drop_column('tickets', 'comentario_calificacion')
    op.drop_column('tickets', 'calificacion')
    op.drop_column('tickets', 'fecha_primera_respuesta')
    # ### end Alembic commands ###
